//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facebook_Group_Manager {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class SettingsTool : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsTool defaultInstance = ((SettingsTool)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsTool())));
        
        public static SettingsTool Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FacebookCookie {
            get {
                return ((string)(this["FacebookCookie"]));
            }
            set {
                this["FacebookCookie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FacebookToken {
            get {
                return ((string)(this["FacebookToken"]));
            }
            set {
                this["FacebookToken"] = value;
            }
        }
    }
}
